### ISSUE TITLE
question not repharaced / addon not working

### ISSUE THREAD

**Issue by username-8** [petioptrv/ml-tutor#3]
i installed & an it, it did not change ethe question in any way. 
does this not work on windows ?  should restart the widow ? . i have an open ai account, i have sufficient balance.. 
please, make a better read me or walk through screen recording.

**Comment by petioptrv** [comment]
@username-8, I updated the documentation yesterday with more details on the configurations. In short, you have to play around with the ease settings (how well you have learned a card before the add-on rephrases it) because the prior defaults were too high and that resulted in cards never being rephrased.

I've also updated the defaults for those settings to more sensible ones.
